---

# https://github.com/ansible/ansible/issues/16884#issuecomment-278138707
- name: "FIX: Ubuntu 16.04 LTS doesn't come with certain modules, required by ansible"
  apt:
    force_apt_get: yes
    name:
      - python-minimal
      - aptitude
    state: present

- name: upgrade all apt packages to the latest version
  apt:
    name: '*'
    state: latest
    update_cache: yes
  when: apt_initial_upgrade_packages

- import_tasks: 'sublime-text.yml'
- import_tasks: 'gcc.yml'